
services:
  
  database:
    container_name: db-users
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - backend-users:/var/lib/postgresql/data

volumes:
  backend-users:
    external: false




