server:
  servlet:
    context-path: /users
  port: 0

spring:
  application:
    name: users
  
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lon:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug


eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Variable de entorno
application:
  auth:
    secret: 0719f088cd49a3f9d1dac2386cbf91d2cd5386776a8577d9b43c0f8ca7f3e308