spring:
  application:
    name: users
  
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lon:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
